-- use `shoponline`;
-- insert into `clients`('address','email','name') values
-- ('Бейкер-стрит, 221b','Sherlockgmail.com','Sherlock'),
-- ('England, Hogwards','HarryPottergmail.com','Harry Potter');
--
-- insert into `products`('name','description','price','amount','image.png','types') values
-- ('phone','iphoneX',1500,5,'some','PHONE');
